export const SET_CURRENT_SONG='SET_CURRENT_SONG'

export const SET_FULL_SCREEN='SET_FULL_SCREEN'

export const SET_PLAYING_STATE='SET_PLAYING_STATE'

export const SET_SEQUECE_PLAYLIST='SET_SEQUECE_PLAYLIST'

export const SET_PLAYLIST='SET_PLAYLIST'

export const SET_PLAY_MODE='SET_PLAY_MODE'

export const SET_CURRYENT_INDEX='SET_CURRYENT_INDEX'

export const SET_SHOW_PLAYLIST='SET_SHOW_PLAYLIST'

export const DELETE_SONG = 'player/DELETE_SONG';

export const INSERT_SONG = 'player/INSERT_SONG';